name: Publish Image Using latest

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Publish Image using latest tag
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'target/test-reports/TEST-*.xml'
      - name: Build
        run: sbt -v -Dfile.encoding=UTF-8 +universal:packageZipTarball
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/ferload
          tag_format: "latest"