
name: Test, Build and Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'target/test-reports/TEST-*.xml'
      - name: Build
        run: sbt -v -Dfile.encoding=UTF-8 +universal:packageZipTarball
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Publish the image
        run: ./push_image.sh